# Generated by Django 5.2.14 on 2026-06-14 11:21

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('duration', models.PositiveIntegerField(help_text='مدت زمان به دقیقه', verbose_name='مدت زمان')),
                ('reserve_fee', models.IntegerField(verbose_name='مبلغ رزرو')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='salon.category', verbose_name='دسته\u200cبندی')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_gap_between_appointments', models.PositiveIntegerField(default=0, help_text='فاصله بین نوبت\u200cها به دقیقه', verbose_name='فاصله بین نوبت\u200cها')),
                ('service', models.ManyToManyField(related_name='staff', to='salon.service', verbose_name='سرویس')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('status', models.CharField(choices=[('available', 'در دسترس'), ('reserved', 'رزرو شده'), ('blocked', 'مسدود شده')], max_length=9, verbose_name='وضعیت')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='salon.availability', verbose_name='دسترسی')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.staff', verbose_name='پرسنل')),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='salon.staff', verbose_name='پرسنل'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_source', models.CharField(choices=[('online', 'آنلاین'), ('walk_in', 'مراجعه حضوری'), ('phone', 'تلفنی')], max_length=7, verbose_name='منبع رزرو')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.service', verbose_name='سرویس')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salon.slot', verbose_name='بازه زمانی')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salon.staff', verbose_name='پرسنل')),
            ],
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('staff', 'date', 'start_time'), name='unique_slot_per_staff'),
        ),
    ]
