# Generated by Django 5.2.14 on 2026-06-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='svg/'),
        ),
    ]
