# Generated by Django 5.2.14 on 2026-06-05 08:51

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_source',
            field=models.CharField(choices=[('online', 'Online'), ('walk_in', 'Walk in'), ('phone', 'Phone')], max_length=7, verbose_name='booking source'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datetime created'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='datetime modified'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.service', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salon.slot', verbose_name='slot'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salon.staff', verbose_name='staff'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='salon.staff', verbose_name='staff'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='salon.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes', verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='service',
            name='reserve_fee',
            field=models.IntegerField(verbose_name='reserve_fee'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='salon.availability', verbose_name='availability'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.staff', verbose_name='staff'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('blocked', 'Blocked')], max_length=9, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='min_gap_between_appointments',
            field=models.PositiveIntegerField(default=0, help_text='Gap between appointments in minutes', verbose_name='gap between appointments'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='service',
            field=models.ManyToManyField(related_name='staff', to='salon.service', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
