# Generated by Django 5.2.14 on 2026-06-08 09:34

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_alter_appointment_booking_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='total_fee',
            field=models.IntegerField(default=1, verbose_name='total_fee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booking_source',
            field=models.CharField(choices=[('online', 'آنلاین'), ('walk_in', 'مراجعه حضوری'), ('phone', 'تلفنی')], max_length=7, verbose_name='منبع رزرو'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.service', verbose_name='سرویس'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salon.slot', verbose_name='بازه زمانی'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salon.staff', verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='salon.staff', verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='salon.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(help_text='مدت زمان به دقیقه', verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='service',
            name='reserve_fee',
            field=models.IntegerField(verbose_name='مبلغ رزرو'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='salon.availability', verbose_name='دسترسی'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.staff', verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('available', 'در دسترس'), ('reserved', 'رزرو شده'), ('blocked', 'مسدود شده')], max_length=9, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='min_gap_between_appointments',
            field=models.PositiveIntegerField(default=0, help_text='فاصله بین نوبت\u200cها به دقیقه', verbose_name='فاصله بین نوبت\u200cها'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='service',
            field=models.ManyToManyField(related_name='staff', to='salon.service', verbose_name='سرویس'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
