# Generated by Django 5.2.14 on 2026-06-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_category_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='svg/'),
        ),
    ]
