# Generated by Django 5.2.14 on 2026-06-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_service_total_fee_alter_appointment_booking_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='total_fee',
        ),
    ]
