# Generated by Django 5.2.14 on 2026-06-09 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0004_remove_service_total_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='payment status')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='total price')),
                ('transaction_datetime', models.DateTimeField(blank=True, null=True, verbose_name='transaction datetime')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('unit_price', models.PositiveIntegerField(verbose_name='unit price')),
                ('total_price', models.PositiveIntegerField(verbose_name='total price')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='salon.appointment', verbose_name='appointment')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment.factor', verbose_name='factor')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_authority', models.CharField(blank=True, max_length=255, null=True, verbose_name='payment authority')),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='reference id')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='gateway code')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='error message')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='gateway response')),
                ('payment_datetime', models.DateTimeField(auto_now_add=True, verbose_name='payment datetime')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.factor', verbose_name='factor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
