# Generated by Django 5.2.14 on 2026-05-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='category_svg/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='service_svg/'),
        ),
    ]
