# Generated by Django 5.2.14 on 2026-06-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='service',
            field=models.ManyToManyField(related_name='staff', to='core.service'),
        ),
    ]
