# Generated by Django 5.2.14 on 2026-05-18 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 18, 10, 6, 53, 52067, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
