# Generated by Django 5.2.14 on 2026-05-26 18:55

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
